### ISSUE TITLE
the url for downing pretrained model can not be found

### ISSUE THREAD

**Issue by XavierLinNow** [wanglimin/ARTNet#10]
Could you offer a new url for pretrained model? Thanks

**Comment by wanglimin** [comment]
Please refer to the following link:

http://mcg.nju.edu.cn/models/ARTNet/112_c3d_resnet_18_kinetics.caffemodel
http://mcg.nju.edu.cn/models/ARTNet/112_artnet_resnet_18_kinetics.caffemodel
http://mcg.nju.edu.cn/models/ARTNet/112_artnet_tsn_resnet_18_kinetics.caffemodel
