### ISSUE TITLE
how_to_make_with_python

### ISSUE THREAD

**Issue by 3DMM-ICME2023** [wanglimin/ARTNet#6]
@wanglimin Thanks for your nice works!
When I use cmake tools(cmake .. -DUSE_MPI=ON -DMPI_CXX_COMPILER=" /usr/local/bin/mpicxx")to complile the ARTNet code, i see the following logs:
-- Could NOT find Boost
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Python interface is disabled or not all required dependecies found. Building without it...

Thus, I can not make caffe with python and import caffe successfully. Could you please help me to build it with python?  Using make rather than cmake? Thanks in advance!

**Comment by wanglimin** [comment]
According to cmake file, you need to install the lib of Boost:

https://github.com/yjxiong/caffe/blob/action_recog/cmake/Dependencies.cmake#L104
