### ISSUE TITLE
new_length in the "C3D_ResNet18 Flow" experiment

### ISSUE THREAD

**Issue by SmartPorridge** [wanglimin/ARTNet#7]
Hi,
In your paper, you report a top-1 error of 42.5% when using C3D_ResNet18 with Flow Modality in Table 3.
Could you tell which new_length you use to do the experiment, 8 or 16 ,or other length?

Thank you.

**Comment by wanglimin** [comment]
It uses the length of 16.

**Comment by SmartPorridge** [comment]
Thank you
